// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.15.6
// source: rpc/kasada.proto

package grpc_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Define Stream KpsdkCtRequest Request
type StreamKpsdkCtRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobId       string `protobuf:"bytes,1,opt,name=jobId,proto3" json:"jobId,omitempty"`
	ControlFlow string `protobuf:"bytes,2,opt,name=controlFlow,proto3" json:"controlFlow,omitempty"`
}

func (x *StreamKpsdkCtRequest) Reset() {
	*x = StreamKpsdkCtRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_kasada_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamKpsdkCtRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamKpsdkCtRequest) ProtoMessage() {}

func (x *StreamKpsdkCtRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_kasada_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamKpsdkCtRequest.ProtoReflect.Descriptor instead.
func (*StreamKpsdkCtRequest) Descriptor() ([]byte, []int) {
	return file_rpc_kasada_proto_rawDescGZIP(), []int{0}
}

func (x *StreamKpsdkCtRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *StreamKpsdkCtRequest) GetControlFlow() string {
	if x != nil {
		return x.ControlFlow
	}
	return ""
}

// Define Stream KpsdkCtResponse Response
type StreamKpsdkCtResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobId   string  `protobuf:"bytes,1,opt,name=jobId,proto3" json:"jobId,omitempty"`
	KpsdkCt string  `protobuf:"bytes,2,opt,name=kpsdkCt,proto3" json:"kpsdkCt,omitempty"`
	TlArray []int64 `protobuf:"varint,3,rep,packed,name=tlArray,proto3" json:"tlArray,omitempty"`
	Errors  *Errors `protobuf:"bytes,4,opt,name=errors,proto3" json:"errors,omitempty"`
}

func (x *StreamKpsdkCtResponse) Reset() {
	*x = StreamKpsdkCtResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_kasada_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamKpsdkCtResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamKpsdkCtResponse) ProtoMessage() {}

func (x *StreamKpsdkCtResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_kasada_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamKpsdkCtResponse.ProtoReflect.Descriptor instead.
func (*StreamKpsdkCtResponse) Descriptor() ([]byte, []int) {
	return file_rpc_kasada_proto_rawDescGZIP(), []int{1}
}

func (x *StreamKpsdkCtResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *StreamKpsdkCtResponse) GetKpsdkCt() string {
	if x != nil {
		return x.KpsdkCt
	}
	return ""
}

func (x *StreamKpsdkCtResponse) GetTlArray() []int64 {
	if x != nil {
		return x.TlArray
	}
	return nil
}

func (x *StreamKpsdkCtResponse) GetErrors() *Errors {
	if x != nil {
		return x.Errors
	}
	return nil
}

var File_rpc_kasada_proto protoreflect.FileDescriptor

var file_rpc_kasada_proto_rawDesc = []byte{
	0x0a, 0x10, 0x72, 0x70, 0x63, 0x2f, 0x6b, 0x61, 0x73, 0x61, 0x64, 0x61, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x1a, 0x10, 0x72, 0x70,
	0x63, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4e,
	0x0a, 0x14, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x4b, 0x70, 0x73, 0x64, 0x6b, 0x43, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6a, 0x6f, 0x62, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6a, 0x6f, 0x62, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b,
	0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x46, 0x6c, 0x6f, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x46, 0x6c, 0x6f, 0x77, 0x22, 0x8b,
	0x01, 0x0a, 0x15, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x4b, 0x70, 0x73, 0x64, 0x6b, 0x43, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6a, 0x6f, 0x62, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6a, 0x6f, 0x62, 0x49, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x6b, 0x70, 0x73, 0x64, 0x6b, 0x43, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6b, 0x70, 0x73, 0x64, 0x6b, 0x43, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x6c, 0x41, 0x72,
	0x72, 0x61, 0x79, 0x18, 0x03, 0x20, 0x03, 0x28, 0x03, 0x52, 0x07, 0x74, 0x6c, 0x41, 0x72, 0x72,
	0x61, 0x79, 0x12, 0x28, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x73, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x42, 0x12, 0x5a, 0x10,
	0x72, 0x70, 0x63, 0x3b, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_kasada_proto_rawDescOnce sync.Once
	file_rpc_kasada_proto_rawDescData = file_rpc_kasada_proto_rawDesc
)

func file_rpc_kasada_proto_rawDescGZIP() []byte {
	file_rpc_kasada_proto_rawDescOnce.Do(func() {
		file_rpc_kasada_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_kasada_proto_rawDescData)
	})
	return file_rpc_kasada_proto_rawDescData
}

var file_rpc_kasada_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_kasada_proto_goTypes = []interface{}{
	(*StreamKpsdkCtRequest)(nil),  // 0: protobuf.StreamKpsdkCtRequest
	(*StreamKpsdkCtResponse)(nil), // 1: protobuf.StreamKpsdkCtResponse
	(*Errors)(nil),                // 2: protobuf.Errors
}
var file_rpc_kasada_proto_depIdxs = []int32{
	2, // 0: protobuf.StreamKpsdkCtResponse.errors:type_name -> protobuf.Errors
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_kasada_proto_init() }
func file_rpc_kasada_proto_init() {
	if File_rpc_kasada_proto != nil {
		return
	}
	file_rpc_errors_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_rpc_kasada_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamKpsdkCtRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_kasada_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamKpsdkCtResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_kasada_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_kasada_proto_goTypes,
		DependencyIndexes: file_rpc_kasada_proto_depIdxs,
		MessageInfos:      file_rpc_kasada_proto_msgTypes,
	}.Build()
	File_rpc_kasada_proto = out.File
	file_rpc_kasada_proto_rawDesc = nil
	file_rpc_kasada_proto_goTypes = nil
	file_rpc_kasada_proto_depIdxs = nil
}
